version: '3.7'
services:
  phpmyadmin:
    image: 'bitnami/phpmyadmin:4'
    ports:
      - '80'
      - '443'
    depends_on:
      - mariadb
    volumes:
      - 'phpmyadmin_data:/bitnami'
  mariadb:
    image: 'bitnami/mariadb:10.3'
    environment:
      - MARIADB_USER=bn_suitecrm
      - MARIADB_DATABASE=bitnami_suitecrm
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  suitecrm:
    image: 'aptotude/suitecrm'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - SUITECRM_DATABASE_USER=bn_suitecrm
      - SUITECRM_DATABASE_NAME=bitnami_suitecrm
      - ALLOW_EMPTY_PASSWORD=yes
      - SUITECRM_USERNAME=user
      - SUITECRM_PASSWORD=bitnami
    ports:
      - '80'
      - '443'
    volumes:
      - 'suitecrm_data:/bitnami'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  suitecrm_data:
    driver: local
  phpmyadmin_data:
    driver: local
